version: '3'

services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: "zabbix-db"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbixpass"
    ports:
      - "10051:10051"
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.0-latest
    container_name: zabbix-web
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: "zabbix-db"
      ZBX_SERVER_HOST: "zabbix-server"
    ports:
      - "80:80"
    restart: unless-stopped

  zabbix-db:
    image: postgres:alpine
    container_name: zabbix-db
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpass
    restart: unless-stopped
