version: '3'
<<<<<<< HEAD

services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: "zabbix-db"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbixpass"
    ports:
      - "10051:10051"
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.0-latest
    container_name: zabbix-web
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: "zabbix-db"
      ZBX_SERVER_HOST: "zabbix-server"
    ports:
      - "80:80"
    restart: unless-stopped

  zabbix-db:
    image: postgres:alpine
    container_name: zabbix-db
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpass
    restart: unless-stopped
=======
services:
  mariadb:
    image: mariadb:10.5
    container_name: zabbix-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - zabbix_network

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-5.0
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-mariadb
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
      MYSQL_DATABASE: zabbix
    ports:
      - "10051:10051"
    networks:
      - zabbix_network
    depends_on:
      - mariadb

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-5.0
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: zabbix-mariadb
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
      MYSQL_DATABASE: zabbix
    ports:
      - "8080:8080"
    networks:
      - zabbix_network
    depends_on:
      - zabbix-server

volumes:
  mariadb-data:
networks:
  zabbix_network:
    driver: bridge

>>>>>>> b540b01 (Add docker-compose.yml from EC2)
